Desktop/Django Projects/E_commerce/E_commerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from store.views import DefView
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', DefView.as_view(), name='home')
]





if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/basic_app/urls.py
from basic_app import views
from django.conf.urls import url, include

app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='registration'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^user_logout/$', views.user_logout, name='user_logout'),
    url(r'^special/$', views.special, name='special'),
]

blog_app/urls.py
from django.urls import re_path
from blog_app.views import AboutView, PostListView, PostDetailView, CreatePostView, UpdatePostView, DeletePostView, DeletePostView, CreateProfileView
from blog_site.blog_app.views import DeleteProfileView, add_comment_to_post, comment_remove, publish_post

app_name = 'blog_app'

urlpatterns = [
    re_path(r'^about/$', AboutView.as_view(), name='about'),
    re_path(r'^$', PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='detail'),
    re_path(r'^post/new_post/$', CreatePostView.as_view(), name='create_post'),
    re_path(r'^post/update/(?P<pk>\d+)/edit/$', UpdatePostView.as_view(), name='update_post'),
    re_path(r'^post/(?P<pk>\d+)/delete/$', DeletePostView.as_view(), name='delete_post'),
    re_path(r'^drafts/$', DeletePostView.as_view(), name='drafts'),
    re_path(r'^profile/create/$', CreateProfileView.as_view(), name='create_profile'),
    re_path(r'^profile/(?P<pk>\d+)/delete/$', DeleteProfileView.as_view(), name='delete_profile'),
    re_path(r'^post/(?P<pk>\d+)/comment/$', add_comment_to_post, name='add_comment_to_post'),
    re_path(r'post/(?P<pk>\d+)/remove/$', comment_remove, name='remove_comment'),
    re_path(r'post/(?P<pk>\d+)/publish/$', publish_post, name='publish_post')
]

blog_site/urls.py
from django import views
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    re_path('', views.Index, name='home'),
    path('admin/', admin.site.urls),
    re_path('^blog_app', include('blog_app.urls')),
]

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/basic_app/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # Additional attributes
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True, upload_to='profile_pics')

    def __str__(self):
        return self.user.username

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/basic_app/forms.py
from basic_app.models import UserProfileInfo
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# LOGIN/OUT MODULES
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, '../templates/basic_app/index.html')

@login_required
def special():
    return HttpResponse("You are logged in. Nice!!!")

@login_required
def user_logout(request):
    logout(request)
    # return HttpResponseRedirect(reverse('index'))
    return render(request, '../templates/basic_app/logout.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
                profile.save()
                registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, '../templates/basic_app/registration.html', context={
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered,
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            print('SOMEONE TRIED TO LOGIN AND FAILED')
            print(f"Username: {username}, Password: {password}")
            return HttpResponse('Login Details Invalid.')
            # raise ValidationError("Login Details Invalid", code='invalid_details')

    else:
        return render(request, '../templates/basic_app/login.html', {})

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
  </head>
  <body class="body">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top mb-5 .navbar-nav-scroll">
      <div class="container-fluid">
        <a href="{% url 'index' %}" class="navbar-brand">HOME</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a href="{% url 'admin:index' %}" class="nav-link active"
                >Admin</a
              >
            </li>
            <li class="nav-item">
              <a href="{% url 'basic_app:registration' %}" class="nav-link"
                >Register</a
              >
            </li>

            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'basic_app:user_logout' %}" class="nav-link"
                >Logout</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'basic_app:user_login' %}" class="nav-link"
                >Login</a
              >
            </li>
            {% endif %}
            <li class="nav-item">
                <a href="{% url 'basic_app:special' %}" class="nav-link"
                  >Special</a
                >
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="custom container w-50 mt-5">{% block body_block %} {% endblock %}</div>
  </body>
</html>

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %} 
{% load static %} 
{% block title %}Home{%endblock %} 
{% block body_block%}
<div class="mt-4 p-5 bg-secondary text-white rounded">
  <h1>Welcome to the Home page</h1>
</div>
{% endblock %}

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block title %}Log-In{% endblock %}
{%block body_block %}
<div class="mt-4 p-5 bg-secondary text-white rounded">
  <h1>Login Here</h1>
  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <div class="username mb-3">
      <label for="username">Username: </label>
      <input type="text" id="username" name="username" class="w-75" />
    </div>
    <div class="password mb-3">
      <label for="password">Password: </label>
      <input type="password" id="password" name="password" class="w-75" />
    </div>
    <input type="submit" value="Login" class="btn btn-primary w-25 py-1 px-1" />
  </form>
  <p class="mt-3">
    Don't have an account?
    <a href="{% url 'basic_app:registration' %}">Register Here</a>
  </p>
</div>
{% endblock %}

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/templates/basic_app/logout.html
{% extends "basic_app/base.html" %}
{% block title %}Logout{% endblock %}

{% block body_block %}
<div class="mt-4 p-5 bg-secondary text-white rounded">
    <h1>Thank You For Banking With Us!!!</h1>
</div>
{% endblock %}

Desktop/FULLSTACK/DJANGO/django_level_five/learning_user_auth/templates/basic_app/registration.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %} 
{% load static %} 
{% block title%}Registration{% endblock %} 
{% block body_block %}

<!-- <div class="overflow-auto"> -->
<div class="mt-4 p-5 bg-secondary text-white rounded mb-5">
{% if registered %}
<h1>Thanks for registering!!!</h1>
{% else %}
<h1>Register Here</h1>
<h3>Fill in the form below:</h3>
<form enctype="multipart/form-data" method="post">
    {% csrf_token %} 
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <input class="btn btn-primary" type="submit" value="Register" />
</form>
{% endif %}
</div>
<!-- </div> -->

{% endblock %}